
## ROTAS PARA SALÃO

### Listar todos salões
GET http://localhost:3000/Salao

### Ver um salão
GET http://localhost:3000/Salao/id

### Criar salão
POST http://localhost:3000/Salao
Content-Type: application/json

{
    "nome":"Salao 1",
    "localizacao":"",
    "horario":"",
    "telefone":"942304521",
    "email":"salao@gmail.com",
    "senha":"12345",
    "imagem":"imagem"
}

### Deletar salão
DELETE http://localhost:3000/Salao/id

### Atualizar salão
PATCH http://localhost:3000/Salao/id
Content-Type: application/json

{
    "nome":"Salao 2",
    "localizacao":"",
    "horario":"",
    "telefone":"922304341",
    "email":"salao2@gmail.com",
    "senha":"123453",
    "imagem":"imagem2"
}

## ROTAS PARA SERVIÇO

### Criar serviço
POST http://localhost:3000/servico
Content-Type: application/json

{
    "salaoId":"id",
    "colaboradorId":"id",
    "tipo":"Corte Francês",
    "duracao":30,
    "valor":2000,
    "status":"A"
}